services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    volumes:
      - static-data:/app/src/static/images
    #ports:
    #  - "8000:8000"
    networks:
      - myNetwork
    env_file:
      - .env
  
  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    volumes:
      - static-data:/app/src/static/images
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
  
  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

volumes:
  static-data:

networks:
  myNetwork:
    external: true